en: "en"
vi: "vi"
user:
  length:
    name: 50
    email: 150
    password: 6
    per_page: 5
remember: "1"
tour:
  length: 9
perpage: 3
cols: 30
rows: 10
accept_image: "image/jpeg,image/gif,image/png"
review:
  length: 9999
full: 0
